#'boxscore_index', 'date', 'datetime', 'day', 'extra_points_attempted',
#       'extra_points_made', 'field_goals_attempted', 'field_goals_made',
#       'fourth_down_attempts', 'fourth_down_conversions', 'interceptions',
#       'location', 'opponent_abbr', 'opponent_name', 'overtime',
#       'pass_attempts', 'pass_completion_rate', 'pass_completions',
#       'pass_touchdowns', 'pass_yards', 'pass_yards_per_attempt',
#       'points_allowed', 'points_scored', 'punt_yards', 'punts',
#       'quarterback_rating', 'result', 'rush_attempts', 'rush_touchdowns',
#       'rush_yards', 'rush_yards_per_attempt', 'third_down_attempts',
#       'third_down_conversions', 'time_of_possession', 'times_sacked', 'type',
#       'week', 'yards_lost_from_sacks'

class WeeklyStat:
    def __init__(self, week_from_schedule):
        self.date = week_from_schedule['date']
        self.day  = week_from_schedule['datetime']
        self.day = week_from_schedule['day'], 
        self.extra_points_attempted = week_from_schedule['extra_points_attempted'],
        self.extra_points_made = week_from_schedule['extra_points_made'], 
        self.field_goals_attempted = week_from_schedule['field_goals_attempted'], 
        self.field_goals_made = week_from_schedule['field_goals_made'],
        self.fourth_down_attempts = week_from_schedule['fourth_down_attempts'], 
        self.fourth_down_conversions = week_from_schedule['fourth_down_conversions'], 
        self.interceptions = week_from_schedule['interceptions'],
        self.location = week_from_schedule['location'], 
        self.opponent_abbr = week_from_schedule['opponent_abbr'], 
        self.opponent_name = week_from_schedule['opponent_name'],
        self.overtime = week_from_schedule['overtime'],
        self.pass_attempts = week_from_schedule['pass_attempts'], 
        self.pass_completion_rate = week_from_schedule['pass_completion_rate'],
        self.pass_completions = week_from_schedule['pass_completions'],
        self.pass_touchdowns = week_from_schedule['pass_touchdowns'],
        self.pass_yards = week_from_schedule['pass_yards'],
        self.pass_yards_per_attempt = week_from_schedule['pass_yards_per_attempt'],
        self.points_allowed = week_from_schedule['points_allowed'], 
        self.points_scored = week_from_schedule['points_scored'],
        self.punt_yards = week_from_schedule['punt_yards'],
        self.punts = week_from_schedule['punts'],
        self.quarterback_rating = week_from_schedule['quarterback_rating'],
        self.result = week_from_schedule['result'], 
        self.rush_attempts = week_from_schedule['rush_attempts'], 
        self.rush_touchdowns = week_from_schedule['rush_touchdowns'],
        self.rush_yards = week_from_schedule['rush_yards'], 
        self.rush_yards_per_attempt = week_from_schedule['rush_yards_per_attempt'], 
        self.third_down_attempts = week_from_schedule['third_down_attempts'],
        self.third_down_conversions = week_from_schedule['third_down_conversions'], 
        self.time_of_possession = week_from_schedule['time_of_possession'], 
        self.times_sacked = week_from_schedule['times_sacked'], 
        self.type = week_from_schedule['type'],
        self.week = week_from_schedule['week'], 
        self.yards_lost_from_sacks = week_from_schedule['yards_lost_from_sacks']